# Generated by Django 5.2.8 on 2025-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='dept',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
